name: thrift_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  # Updated fl_chart to the latest version
  fl_chart: ^1.0.0

  # State Management & Core Utilities
  # Updated flutter_bloc and get_it to their latest versions
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.1.0

  # Data & Serialization
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0

  # Utilities
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
    - assets/icons/